/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author oli
 */
public class viewEncarAD extends javax.swing.JFrame {

    /**
     * Creates new form viewAreaAd
     */
    public viewEncarAD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jptitulo = new javax.swing.JPanel();
        lbtitulo = new javax.swing.JLabel();
        btncerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lbap1 = new javax.swing.JLabel();
        txtap1 = new javax.swing.JTextField();
        lbap2 = new javax.swing.JLabel();
        txtap2 = new javax.swing.JTextField();
        lbcargo = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jptitulo.setBackground(new java.awt.Color(0, 123, 255));
        jptitulo.setLayout(new javax.swing.BoxLayout(jptitulo, javax.swing.BoxLayout.LINE_AXIS));

        lbtitulo.setFont(new java.awt.Font("DejaVu Sans", 2, 14)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbtitulo.setText("  Encargado Nuevo                                                      ");
        jptitulo.add(lbtitulo);

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btncerrar.setBorderPainted(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setFocusPainted(false);
        btncerrar.setFocusable(false);
        jptitulo.add(btncerrar);

        jPanel2.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        lbnombre.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbnombre.setText("Nombre");
        jPanel2.add(lbnombre);
        jPanel2.add(txtnombre);

        lbap1.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbap1.setText("Primer apellido");
        jPanel2.add(lbap1);
        jPanel2.add(txtap1);

        lbap2.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbap2.setText("Segundo apellido");
        jPanel2.add(lbap2);
        jPanel2.add(txtap2);

        lbcargo.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbcargo.setText("Cargo");
        jPanel2.add(lbcargo);
        jPanel2.add(txtcargo);

        btncancelar.setBackground(new java.awt.Color(108, 117, 125));
        btncancelar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setBorderPainted(false);
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.setFocusPainted(false);
        btncancelar.setFocusable(false);
        jPanel2.add(btncancelar);

        btnguardar.setBackground(new java.awt.Color(0, 123, 255));
        btnguardar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorderPainted(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setFocusPainted(false);
        btnguardar.setFocusable(false);
        jPanel2.add(btnguardar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jptitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jptitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEncarAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEncarAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEncarAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEncarAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewEncarAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btncerrar;
    public javax.swing.JButton btnguardar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jptitulo;
    private javax.swing.JLabel lbap1;
    private javax.swing.JLabel lbap2;
    private javax.swing.JLabel lbcargo;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTextField txtap1;
    private javax.swing.JTextField txtap2;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
