/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author oliver-1
 */
public class viewPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPPrincipal = new javax.swing.JPanel();
        JPInventario = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btninvetario = new javax.swing.JButton();
        lbinventario = new javax.swing.JLabel();
        JPAreas = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAreas = new javax.swing.JButton();
        lbareas = new javax.swing.JLabel();
        JPEncargados = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnEncar = new javax.swing.JButton();
        lbencargados = new javax.swing.JLabel();
        JPCategorias = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCategory = new javax.swing.JButton();
        lbcategorias = new javax.swing.JLabel();
        JPGpastel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPBarras = new javax.swing.JPanel();

        JPPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        JPInventario.setBackground(new java.awt.Color(255, 255, 255));
        JPInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 126, 20)));
        JPInventario.setPreferredSize(new java.awt.Dimension(150, 100));
        JPInventario.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(253, 126, 20));
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inventario");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        JPInventario.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        btninvetario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas2.png"))); // NOI18N
        btninvetario.setText("Articulos en total");
        btninvetario.setBorder(null);
        btninvetario.setBorderPainted(false);
        btninvetario.setContentAreaFilled(false);
        btninvetario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninvetario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninvetario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JPInventario.add(btninvetario, java.awt.BorderLayout.PAGE_END);

        lbinventario.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lbinventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPInventario.add(lbinventario, java.awt.BorderLayout.CENTER);

        JPAreas.setBackground(new java.awt.Color(255, 255, 255));
        JPAreas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 201, 151)));
        JPAreas.setPreferredSize(new java.awt.Dimension(150, 150));
        JPAreas.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(32, 201, 151));
        jPanel12.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Áreas");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        JPAreas.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        btnAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas5.png"))); // NOI18N
        btnAreas.setText("Áreas en total");
        btnAreas.setBorder(null);
        btnAreas.setBorderPainted(false);
        btnAreas.setContentAreaFilled(false);
        btnAreas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAreas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAreas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JPAreas.add(btnAreas, java.awt.BorderLayout.PAGE_END);

        lbareas.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lbareas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPAreas.add(lbareas, java.awt.BorderLayout.CENTER);

        JPEncargados.setBackground(new java.awt.Color(255, 255, 255));
        JPEncargados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        JPEncargados.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 193, 7));
        jPanel13.setPreferredSize(new java.awt.Dimension(148, 40));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Encargados");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPEncargados.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        btnEncar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas3.png"))); // NOI18N
        btnEncar.setText("Encargados en total");
        btnEncar.setBorder(null);
        btnEncar.setBorderPainted(false);
        btnEncar.setContentAreaFilled(false);
        btnEncar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEncar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JPEncargados.add(btnEncar, java.awt.BorderLayout.PAGE_END);

        lbencargados.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lbencargados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPEncargados.add(lbencargados, java.awt.BorderLayout.CENTER);

        JPCategorias.setBackground(new java.awt.Color(255, 255, 255));
        JPCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 168, 216)));
        JPCategorias.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(32, 168, 216));
        jPanel14.setPreferredSize(new java.awt.Dimension(149, 40));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Categorias");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        JPCategorias.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas4.png"))); // NOI18N
        btnCategory.setText("Categorias en total");
        btnCategory.setBorder(null);
        btnCategory.setBorderPainted(false);
        btnCategory.setContentAreaFilled(false);
        btnCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategory.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JPCategorias.add(btnCategory, java.awt.BorderLayout.PAGE_END);

        lbcategorias.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lbcategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPCategorias.add(lbcategorias, java.awt.BorderLayout.CENTER);

        JPGpastel.setBackground(new java.awt.Color(255, 255, 255));
        JPGpastel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        JPBarras.setBackground(new java.awt.Color(255, 255, 255));
        JPBarras.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(JPBarras);

        javax.swing.GroupLayout JPPrincipalLayout = new javax.swing.GroupLayout(JPPrincipal);
        JPPrincipal.setLayout(JPPrincipalLayout);
        JPPrincipalLayout.setHorizontalGroup(
            JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addComponent(JPInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPEncargados, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addComponent(JPGpastel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        JPPrincipalLayout.setVerticalGroup(
            JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPEncargados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPGpastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPAreas;
    public javax.swing.JPanel JPBarras;
    private javax.swing.JPanel JPCategorias;
    private javax.swing.JPanel JPEncargados;
    public javax.swing.JPanel JPGpastel;
    private javax.swing.JPanel JPInventario;
    public javax.swing.JPanel JPPrincipal;
    public javax.swing.JButton btnAreas;
    public javax.swing.JButton btnCategory;
    public javax.swing.JButton btnEncar;
    public javax.swing.JButton btninvetario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbareas;
    public javax.swing.JLabel lbcategorias;
    public javax.swing.JLabel lbencargados;
    public javax.swing.JLabel lbinventario;
    // End of variables declaration//GEN-END:variables
}
