/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author oli
 */
public class viewAreaAD extends javax.swing.JFrame {

    /**
     * Creates new form viewAreaAD
     */
    public viewAreaAD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jptitulo = new javax.swing.JPanel();
        lbtitulo = new javax.swing.JLabel();
        btncerrar = new javax.swing.JButton();
        jpdatos = new javax.swing.JPanel();
        lbnombre = new javax.swing.JLabel();
        lbespacio = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jpbotones = new javax.swing.JPanel();
        lbespacio2 = new javax.swing.JLabel();
        lbespacio3 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jptitulo.setBackground(new java.awt.Color(0, 123, 255));
        jptitulo.setForeground(new java.awt.Color(255, 255, 255));
        jptitulo.setLayout(new javax.swing.BoxLayout(jptitulo, javax.swing.BoxLayout.LINE_AXIS));

        lbtitulo.setFont(new java.awt.Font("DejaVu Sans", 2, 14)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbtitulo.setText("   Registro Nuevo                                                          ");
        lbtitulo.setPreferredSize(new java.awt.Dimension(200, 15));
        jptitulo.add(lbtitulo);

        btncerrar.setBackground(new java.awt.Color(220, 53, 69));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btncerrar.setBorderPainted(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setFocusPainted(false);
        jptitulo.add(btncerrar);

        jpdatos.setLayout(new java.awt.BorderLayout());

        lbnombre.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbnombre.setText("Nombre");
        lbnombre.setMaximumSize(new java.awt.Dimension(10, 10));
        lbnombre.setMinimumSize(new java.awt.Dimension(10, 10));
        lbnombre.setPreferredSize(new java.awt.Dimension(10, 15));
        jpdatos.add(lbnombre, java.awt.BorderLayout.CENTER);

        lbespacio.setPreferredSize(new java.awt.Dimension(0, 20));
        jpdatos.add(lbespacio, java.awt.BorderLayout.PAGE_START);

        txtnombre.setPreferredSize(new java.awt.Dimension(220, 23));
        jpdatos.add(txtnombre, java.awt.BorderLayout.LINE_END);

        jpbotones.setBackground(new java.awt.Color(255, 255, 255));
        jpbotones.setPreferredSize(new java.awt.Dimension(250, 60));
        jpbotones.setLayout(new java.awt.GridLayout(2, 2, 5, 0));
        jpbotones.add(lbespacio2);
        jpbotones.add(lbespacio3);

        btncancelar.setBackground(new java.awt.Color(108, 117, 125));
        btncancelar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setBorderPainted(false);
        btncancelar.setFocusPainted(false);
        btncancelar.setFocusable(false);
        jpbotones.add(btncancelar);

        btnguardar.setBackground(new java.awt.Color(0, 123, 255));
        btnguardar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorderPainted(false);
        btnguardar.setFocusPainted(false);
        btnguardar.setFocusable(false);
        jpbotones.add(btnguardar);

        jpdatos.add(jpbotones, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jptitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpdatos, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jptitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpdatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAreaAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAreaAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAreaAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAreaAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAreaAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btncerrar;
    public javax.swing.JButton btnguardar;
    private javax.swing.JPanel jpbotones;
    private javax.swing.JPanel jpdatos;
    private javax.swing.JPanel jptitulo;
    private javax.swing.JLabel lbespacio;
    private javax.swing.JLabel lbespacio2;
    private javax.swing.JLabel lbespacio3;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
