/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author oliver-1
 */
public class viewInventario extends javax.swing.JPanel {

    /**
     * Creates new form viewInventario
     */
    public viewInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpinsetar = new javax.swing.JPanel();
        lbcodigo = new javax.swing.JLabel();
        jpcodigo = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        btnauto = new javax.swing.JToggleButton();
        lbcondicion = new javax.swing.JLabel();
        JCondicion = new javax.swing.JComboBox();
        btnguardar = new javax.swing.JButton();
        lbcategoria = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jccategoria = new javax.swing.JComboBox<String>();
        btnMasCateg = new javax.swing.JButton();
        lbarea = new javax.swing.JLabel();
        jparea = new javax.swing.JPanel();
        jcarea = new javax.swing.JComboBox<String>();
        btnMasArea = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        lbdescripcion = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        lbencargado = new javax.swing.JLabel();
        jpencergado = new javax.swing.JPanel();
        jcencargado = new javax.swing.JComboBox<String>();
        btnMasEcgd = new javax.swing.JButton();
        bntmiltiple = new javax.swing.JButton();
        lbmarca = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lbdetalles = new javax.swing.JLabel();
        txtdetalles = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbmodelo = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpbuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttextoE = new javax.swing.JTextField();
        jptabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTDatos = new javax.swing.JTable();
        jpinferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jpinsetar.setBackground(java.awt.Color.white);
        jpinsetar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Nuevo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jpinsetar.setLayout(new java.awt.GridLayout(5, 2, 10, 3));

        lbcodigo.setBackground(java.awt.Color.white);
        lbcodigo.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbcodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbcodigo.setText("Codigo");
        lbcodigo.setAlignmentX(0.5F);
        jpinsetar.add(lbcodigo);

        jpcodigo.setBackground(new java.awt.Color(255, 255, 255));
        jpcodigo.setLayout(new javax.swing.BoxLayout(jpcodigo, javax.swing.BoxLayout.LINE_AXIS));
        jpcodigo.add(txtcodigo);

        btnauto.setBackground(new java.awt.Color(0, 123, 255));
        btnauto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/codigo-de-barras.png"))); // NOI18N
        btnauto.setSelected(true);
        jpcodigo.add(btnauto);

        jpinsetar.add(jpcodigo);

        lbcondicion.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbcondicion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbcondicion.setText("Condicion");
        lbcondicion.setAlignmentX(0.5F);
        jpinsetar.add(lbcondicion);

        JCondicion.setBackground(new java.awt.Color(255, 255, 255));
        JCondicion.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        JCondicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bueno", "Regular  ", "Malo", " " }));
        jpinsetar.add(JCondicion);

        btnguardar.setBackground(new java.awt.Color(52, 58, 64));
        btnguardar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("                 Guardar");
        btnguardar.setAutoscrolls(true);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpinsetar.add(btnguardar);

        lbcategoria.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbcategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbcategoria.setText("Categoria");
        lbcategoria.setAlignmentX(0.5F);
        jpinsetar.add(lbcategoria);

        jPanel1.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jccategoria.setBackground(new java.awt.Color(255, 255, 255));
        jccategoria.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jPanel1.add(jccategoria);

        btnMasCateg.setBackground(new java.awt.Color(0, 123, 255));
        btnMasCateg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        btnMasCateg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnMasCateg);

        jpinsetar.add(jPanel1);

        lbarea.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbarea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbarea.setText("Area");
        lbarea.setAlignmentX(0.5F);
        jpinsetar.add(lbarea);

        jparea.setBackground(new java.awt.Color(255, 255, 255));
        jparea.setPreferredSize(new java.awt.Dimension(10, 20));
        jparea.setLayout(new javax.swing.BoxLayout(jparea, javax.swing.BoxLayout.LINE_AXIS));

        jcarea.setBackground(new java.awt.Color(255, 255, 255));
        jcarea.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jcarea.setPreferredSize(new java.awt.Dimension(54, 25));
        jparea.add(jcarea);

        btnMasArea.setBackground(new java.awt.Color(0, 123, 255));
        btnMasArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jparea.add(btnMasArea);

        jpinsetar.add(jparea);

        btnlimpiar.setBackground(new java.awt.Color(52, 58, 64));
        btnlimpiar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnlimpiar.setText("                  Limpiar");
        btnlimpiar.setBorderPainted(false);
        jpinsetar.add(btnlimpiar);

        lbdescripcion.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbdescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbdescripcion.setText("Descripcion");
        lbdescripcion.setAlignmentX(0.5F);
        jpinsetar.add(lbdescripcion);
        jpinsetar.add(txtdescripcion);

        lbencargado.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbencargado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbencargado.setText("Encargado");
        lbencargado.setAlignmentX(0.5F);
        jpinsetar.add(lbencargado);

        jpencergado.setBackground(new java.awt.Color(255, 255, 255));
        jpencergado.setLayout(new javax.swing.BoxLayout(jpencergado, javax.swing.BoxLayout.LINE_AXIS));

        jcencargado.setBackground(new java.awt.Color(255, 255, 255));
        jcencargado.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jpencergado.add(jcencargado);

        btnMasEcgd.setBackground(new java.awt.Color(0, 123, 255));
        btnMasEcgd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jpencergado.add(btnMasEcgd);

        jpinsetar.add(jpencergado);

        bntmiltiple.setBackground(new java.awt.Color(52, 58, 64));
        bntmiltiple.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        bntmiltiple.setForeground(new java.awt.Color(255, 255, 255));
        bntmiltiple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiples.png"))); // NOI18N
        bntmiltiple.setText("                  Multiple");
        jpinsetar.add(bntmiltiple);

        lbmarca.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbmarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbmarca.setText("Marca");
        lbmarca.setAlignmentX(0.5F);
        jpinsetar.add(lbmarca);
        jpinsetar.add(txtmarca);

        lbdetalles.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbdetalles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbdetalles.setText("Detalles");
        lbdetalles.setAlignmentX(0.5F);
        jpinsetar.add(lbdetalles);
        jpinsetar.add(txtdetalles);
        jpinsetar.add(jLabel6);

        lbmodelo.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lbmodelo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbmodelo.setText("Modelo");
        lbmodelo.setAlignmentX(0.5F);
        jpinsetar.add(lbmodelo);
        jpinsetar.add(txtmodelo);

        jLabel4.setAlignmentX(0.5F);
        jpinsetar.add(jLabel4);
        jpinsetar.add(jLabel5);

        jpbuscar.setBackground(java.awt.Color.white);
        jpbuscar.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel7.setText("Mostrar");
        jpbuscar.add(jLabel7);

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "25", "50", "100" }));
        jpbuscar.add(jComboBox2);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel8.setText("Registros");
        jpbuscar.add(jLabel8);
        jpbuscar.add(jLabel3);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel2.setText("Buscar");
        jpbuscar.add(jLabel2);
        jpbuscar.add(txttextoE);

        jptabla.setBackground(java.awt.Color.white);
        jptabla.setLayout(new java.awt.BorderLayout());

        JTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTDatos);

        jptabla.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jpinferior.setBackground(new java.awt.Color(255, 255, 255));
        jpinferior.setLayout(new javax.swing.BoxLayout(jpinferior, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel1.setText("Mostrando 1 a 10 registros de 78");
        jpinferior.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                    .addComponent(jptabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpinferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpinsetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jpbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jptabla, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpinferior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpinsetar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox JCondicion;
    public javax.swing.JTable JTDatos;
    public javax.swing.JButton bntmiltiple;
    public javax.swing.JButton btnMasArea;
    public javax.swing.JButton btnMasCateg;
    public javax.swing.JButton btnMasEcgd;
    public javax.swing.JToggleButton btnauto;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> jcarea;
    public javax.swing.JComboBox<String> jccategoria;
    public javax.swing.JComboBox<String> jcencargado;
    private javax.swing.JPanel jparea;
    private javax.swing.JPanel jpbuscar;
    private javax.swing.JPanel jpcodigo;
    private javax.swing.JPanel jpencergado;
    private javax.swing.JPanel jpinferior;
    private javax.swing.JPanel jpinsetar;
    private javax.swing.JPanel jptabla;
    private javax.swing.JLabel lbarea;
    private javax.swing.JLabel lbcategoria;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JLabel lbcondicion;
    private javax.swing.JLabel lbdescripcion;
    private javax.swing.JLabel lbdetalles;
    private javax.swing.JLabel lbencargado;
    private javax.swing.JLabel lbmarca;
    private javax.swing.JLabel lbmodelo;
    public javax.swing.JTextField txtcodigo;
    public javax.swing.JTextField txtdescripcion;
    public javax.swing.JTextField txtdetalles;
    public javax.swing.JTextField txtmarca;
    public javax.swing.JTextField txtmodelo;
    public javax.swing.JTextField txttextoE;
    // End of variables declaration//GEN-END:variables
}
